# server {
#     listen 80;
#     server_name talenttos.ddns.net www.talenttos.ddns.net;

#     root /var/www/html/public;
#     index index.php index.html;

#     location / {
#         try_files $uri /index.php$is_args$args;
#     }

#     location ^~ /.well-known/acme-challenge/ {
#         alias /var/www/certbot/.well-known/acme-challenge/;
#         default_type "text/plain";
#         try_files $uri =404;
#     }


#     location ~ ^/index\.php(/|$) {
#         fastcgi_pass php:9000;
#         fastcgi_split_path_info ^(.+\.php)(/.*)$;
#         include fastcgi_params;
#         fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
#         fastcgi_param DOCUMENT_ROOT $realpath_root;
#         internal;
#     }

#     location ~ \.php$ {
#         return 404;
#     }

#     client_max_body_size 20M;
# }


server {
    listen 80;
    server_name talenttos.ddns.net;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name talenttos.ddns.net;

    ssl_certificate /etc/letsencrypt/live/talenttos.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/talenttos.ddns.net/privkey.pem;

    root /var/www/html/public;
    index index.php index.html;

    # Symfony app
    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ \.php$ {
        return 404;
    }

    # =========================
    # JANUS HTTP API
    # =========================
    location /janus {
        proxy_pass http://host.docker.internal:8088;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # =========================
    # JANUS WebSocket
    # =========================
    location /chat-ws {
        proxy_pass http://host.docker.internal:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    client_max_body_size 20M;
}